spring.application.name=flower-management

server.port=3636

spring.datasource.url=jdbc:postgresql://localhost:5432/flower_management
spring.datasource.username=conmamnam
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.charSet=UTF-8

# Session Configuration - Gio hang luu trong session (timeout 1 gio)
server.servlet.session.timeout=3600s
server.servlet.session.cookie.name=CART_SESSION
server.servlet.session.cookie.max-age=3600

# ================== VNPay Sandbox Configuration ==================
vnpay.tmn-code=BB0JYYQ6
vnpay.hash-secret=OB7994OBNSP4QGM4QQUV07XZA212Y3G2
vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://10.0.250.146:3636/payment/vnpayReturn

# ================== SMTP Configuration ==================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vinhhaphoi@gmail.com
spring.mail.password=ersy amhf pycf ujon
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================== Redis Configuration ==================
spring.data.redis.host=localhost
spring.data.redis.port=6379